# This is the compose file for the server
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arman -d no_spoil_alert"]
      interval: 3s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  # Simple web UI at http://localhost:8080
  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  no_spoil_alert:
    image: ghcr.io/armandris/no_spoil_alert@${NO_SPOIL_ALERT_DIGEST}
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck.sh"]
      interval: 3s
      timeout: 3s
      retries: 20
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:


