name: Build container image
on:
  push:
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . \
          --file Dockerfile \
          --tag no_spoil_alert \
          --build-arg GIT_SHA="${{ github.sha }}" \
          --build-arg BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"


      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/armandris/no_spoil_alert
          TAG="$IMAGE_ID":$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Push with version tag
          docker tag no_spoil_alert "$TAG"
          docker push "$TAG"
          # Also push with production tag
          docker tag no_spoil_alert "$IMAGE_ID:production"
          docker push "$IMAGE_ID:production"
